### ISSUE TITLE
需修正部分

### ISSUE THREAD

**Issue by ac9607** [godfat/cultivate#1]
1. 在Comment裡面會有些, /n的符號破壞 通常這種Comment都不重要 可以考慮直接重新讀取後面的Date再存 因為Date格式非常固定 或者讀到 105. 106. 107.才能算新的一筆資料

2. 藥敏的部份因為Patient ID會重複，REQ+Date會比較合適 另外因為上面的格子有歪掉 裡面有存了"R28216" "3"  這種看起來是被擠過來的東西

3. 這個可以之後再弄 如果可以的話 藥敏結果 可以拆解成三個部分 存
例如 PENG(>=0.5 R) 就是 測試名稱 PENG (一定有) >=0.5 (數字，不一定有)  (判讀，可能是 +, -, S, I, R等符號，不一定有)

4. 出現 Identification by MALDI-TOF. AST ongoing. 這個一定是初步報告，我稍微查一下，我怕現在會只存到初步 (沒有藥敏) 而沒有把後來的正式存進去？

**Comment by godfat** [comment]
@ac9607 REQ 是什麼？reqno？ Date 是簽收還是申請？

**Comment by godfat** [comment]
有人的 reqno 是空的哩，有其他保證有的資料嗎？

**Comment by ac9607** [comment]
reqno如果是空的表示歪掉了 理論上是不可能沒有
不過我看到前面有幾份檔案整排不見....我研究一下

**Comment by ac9607** [comment]
真的有幾份檔案不見了 囧 這不應該發生 不知道檔案輸出出了什麼問題 因為reqno的確算是醫院內部辨識用的ID 不可能沒有
那用簽收日期+流水號好了

**Comment by godfat** [comment]
基本上這樣就等於是沒有任何可以辨認的編號說（基本上就是只有自動產生的流水號）。當然也不是不行，就是沒辦法更新資料，只能不斷新增。但更大的問題是，我看了一下 reqno 不見的那筆，基本上整筆的資料看起來都很怪，應該就是因為歪掉造成的。問題是我看不出來歪掉的規律是什麼，這樣要修復也很難修復...

最糟的情況大概就是，那些資料全部忽略不存吧 @@

**Comment by godfat** [comment]
0. Fixed https://github.com/godfat/cultivate/commit/d09f7a4eca1f5c10ed42dca3a079c444f2032fae
0. 改用 serialno + application_date, 因為 reqno 可能會是空的
0. 等確認其他無誤再來處理這個
0. 等確認其他無誤再來處理這個

**Comment by godfat** [comment]
Splitting 3 to https://github.com/godfat/cultivate/issues/3

Not sure about 4, assuming fixed or raised by the other issue.

Closing
