### ISSUE TITLE
NewBig5toUTF-8 cause error

### ISSUE THREAD

**Issue by ac9607** [godfat/cultivate#5]
Error log

./bin/big5-to-utf8 /Users/wangyp/Documents/cultivate/data20180831
	5: from ./bin/big5-to-utf8:5:in `<main>'
	4: from /Users/wangyp/Documents/cultivate/lib/cultivate.rb:11:in `traverse'
	3: from /Users/wangyp/Documents/cultivate/lib/cultivate.rb:11:in `each'
	2: from /Users/wangyp/Documents/cultivate/lib/cultivate.rb:15:in `block in traverse'
	1: from /Users/wangyp/Documents/cultivate/lib/cultivate.rb:15:in `each'
./bin/big5-to-utf8:8:in `block in <main>': undefined method `encode' for 27339:Integer (NoMethodError)

**Comment by godfat** [comment]
Fixed my stupid typo :/
