### ISSUE TITLE
Error with latest version of Ruby

### ISSUE THREAD

**Issue by ac9607** [godfat/cultivate#8]
wangyp@wangyps-MacBook-Pro-2 cultivate-master6 % ./bin/import /Users/wangyp/Downloads/cultivate-master6/new       
This was tested on Ruby 2.5.3, but you're using 2.6.3
invalid byte sequence in UTF-8
File: /Users/wangyp/Downloads/cultivate-master6/new/%e5%be%ae%e7%94%9f%e7%89%a9%e4%b8%80%e8%88%ac%e5%9f%b9%e9%a4%8a%e7%b5%90%e6%9e%9c1090508.csv
Traceback (most recent call last):
	7: from ./bin/import:7:in `<main>'
	6: from /Users/wangyp/Downloads/cultivate-master6/lib/cultivate.rb:11:in `traverse'
	5: from /Users/wangyp/Downloads/cultivate-master6/lib/cultivate.rb:11:in `each'
	4: from /Users/wangyp/Downloads/cultivate-master6/lib/cultivate.rb:15:in `block in traverse'
	3: from /Users/wangyp/Downloads/cultivate-master6/lib/cultivate.rb:15:in `each'
	2: from ./bin/import:8:in `block in <main>'
	1: from /Users/wangyp/Downloads/cultivate-master6/lib/cultivate/model.rb:20:in `import'
/Users/wangyp/Downloads/cultivate-master6/lib/cultivate/model.rb:40:in `load_rows': undefined method `drop' for nil:NilClass (NoMethodError)

I sent the latest file for you as example file through facebook

**Comment by godfat** [comment]
I just pushed https://github.com/godfat/cultivate/commit/47ce1474e850b72649376752d8ab091be7d0b200 which will try to transcode from BIG5-UAO to UTF-8 again, which should be more robust and you'll no longer need to transcode to UTF-8 first before feeding it.

All the sample files worked without errors. Let me know how this works.

**Comment by godfat** [comment]
Closing as the current files are working
